version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8081:5000"
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - "8088:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    volumes:
      - ./WebApp/db/init.sql:/docker-entrypoint-initdb.d/init.sql
